-- Migration 053: Magic Link Invites
-- Replace code-based invites with Supabase magic link (one-time login links)
-- Store simple random numbers for easy sharing and tracking

CREATE TABLE IF NOT EXISTS public.magic_link_invites (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  phone_number TEXT,
  role VARCHAR(50) DEFAULT 'member',
  invite_number VARCHAR(10) NOT NULL UNIQUE, -- Simple random number like "8374629"
  magic_link TEXT, -- The actual Supabase magic link (generated by auth)
  status VARCHAR(30) DEFAULT 'pending', -- pending, sent, used, expired, revoked
  created_by INTEGER REFERENCES public.members(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  sent_at TIMESTAMPTZ, -- When the magic link was actually sent
  expires_at TIMESTAMPTZ, -- When the invite expires
  used_at TIMESTAMPTZ, -- When the invite was used
  used_by INTEGER REFERENCES public.members(id) ON DELETE SET NULL,
  notes TEXT
);

-- Create indexes for quick lookups
CREATE INDEX IF NOT EXISTS idx_magic_link_invites_tenant ON public.magic_link_invites(tenant_id);
CREATE INDEX IF NOT EXISTS idx_magic_link_invites_email ON public.magic_link_invites(email);
CREATE INDEX IF NOT EXISTS idx_magic_link_invites_number ON public.magic_link_invites(invite_number);
CREATE INDEX IF NOT EXISTS idx_magic_link_invites_status ON public.magic_link_invites(status);

-- Enable RLS
ALTER TABLE public.magic_link_invites ENABLE ROW LEVEL SECURITY;

-- Admins can manage magic link invites
DROP POLICY IF EXISTS "Admins can manage magic link invites" ON public.magic_link_invites;
CREATE POLICY "Admins can manage magic link invites" ON public.magic_link_invites
FOR ALL
USING (public.is_admin())
WITH CHECK (public.is_admin());

-- Add comment
COMMENT ON TABLE public.magic_link_invites IS 'Magic link invites with simple invite numbers for easy sharing';
COMMENT ON COLUMN public.magic_link_invites.invite_number IS 'Simple random number (e.g., 8374629) for easy sharing';
COMMENT ON COLUMN public.magic_link_invites.magic_link IS 'Supabase magic link URL with one-time login token';

-- RPC function to generate a simple invite number
CREATE OR REPLACE FUNCTION public.generate_invite_number()
RETURNS TEXT
LANGUAGE plpgsql
AS $function$
DECLARE
  invite_num TEXT;
BEGIN
  -- Generate a random 7-digit number
  invite_num := LPAD((FLOOR(RANDOM() * 10000000)::INTEGER)::TEXT, 7, '0');
  RETURN invite_num;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.generate_invite_number() TO authenticated, anon;

-- RPC function to verify a magic link invite by invite number
CREATE OR REPLACE FUNCTION public.verify_magic_link_invite(p_invite_number TEXT)
RETURNS TABLE (
  id UUID,
  tenant_id UUID,
  email TEXT,
  phone_number TEXT,
  role VARCHAR,
  invite_number VARCHAR,
  status VARCHAR,
  created_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  RETURN QUERY
  SELECT
    mli.id,
    mli.tenant_id,
    mli.email,
    mli.phone_number,
    mli.role,
    mli.invite_number,
    mli.status,
    mli.created_at,
    mli.expires_at
  FROM public.magic_link_invites mli
  WHERE mli.invite_number = p_invite_number
    AND mli.status = 'sent'
    AND (mli.expires_at IS NULL OR mli.expires_at > NOW());
END;
$function$;

GRANT EXECUTE ON FUNCTION public.verify_magic_link_invite(TEXT) TO authenticated, anon;

-- RPC function to mark a magic link invite as used
CREATE OR REPLACE FUNCTION public.mark_magic_link_invite_used(p_invite_id UUID, p_member_id INTEGER)
RETURNS TABLE (
  id UUID,
  status VARCHAR,
  used_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  RETURN QUERY
  UPDATE public.magic_link_invites
  SET
    status = 'used',
    used_at = NOW(),
    used_by = p_member_id
  WHERE id = p_invite_id
  RETURNING id, status, used_at;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.mark_magic_link_invite_used(UUID, INTEGER) TO authenticated, anon;

