-- Migration 085: Internal admin shell console (command bus)
--
-- Adds:
-- 1) admin_shell_sessions: per-admin shell sessions
-- 2) admin_shell_commands: queued/running/completed command records
-- 3) admin_shell_output: append-only shell output stream
-- 4) RLS policies limited to internal admins and their own sessions

create extension if not exists "pgcrypto";

create table if not exists public.admin_shell_sessions (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid references public.tenants(id) on delete set null,
  status text not null default 'open',
  title text,
  metadata jsonb not null default '{}'::jsonb,
  created_by_auth_id uuid not null default auth.uid(),
  actor_member_id integer references public.members(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint admin_shell_sessions_status_check
    check (lower(status) in ('open', 'closed', 'expired'))
);

create index if not exists admin_shell_sessions_created_by_idx
  on public.admin_shell_sessions (created_by_auth_id, created_at desc);

create index if not exists admin_shell_sessions_tenant_idx
  on public.admin_shell_sessions (tenant_id, created_at desc);

create table if not exists public.admin_shell_commands (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.admin_shell_sessions(id) on delete cascade,
  command_text text not null,
  normalized_command text,
  status text not null default 'queued',
  cancel_requested boolean not null default false,
  exit_code integer,
  error_text text,
  metadata jsonb not null default '{}'::jsonb,
  created_by_auth_id uuid not null default auth.uid(),
  created_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint admin_shell_commands_status_check
    check (lower(status) in ('queued', 'running', 'succeeded', 'failed', 'cancelled'))
);

create index if not exists admin_shell_commands_session_created_idx
  on public.admin_shell_commands (session_id, created_at desc);

create index if not exists admin_shell_commands_session_status_idx
  on public.admin_shell_commands (session_id, status, created_at desc);

create table if not exists public.admin_shell_output (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.admin_shell_sessions(id) on delete cascade,
  command_id uuid references public.admin_shell_commands(id) on delete set null,
  stream text not null default 'system',
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_by_auth_id uuid not null default auth.uid(),
  created_at timestamptz not null default now(),
  constraint admin_shell_output_stream_check
    check (lower(stream) in ('stdin', 'stdout', 'stderr', 'system'))
);

create index if not exists admin_shell_output_session_id_idx
  on public.admin_shell_output (session_id, id asc);

create index if not exists admin_shell_output_command_id_idx
  on public.admin_shell_output (command_id, id asc);

create or replace function public.admin_shell_touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_admin_shell_sessions_touch_updated_at on public.admin_shell_sessions;
create trigger trg_admin_shell_sessions_touch_updated_at
before update on public.admin_shell_sessions
for each row execute function public.admin_shell_touch_updated_at();

drop trigger if exists trg_admin_shell_commands_touch_updated_at on public.admin_shell_commands;
create trigger trg_admin_shell_commands_touch_updated_at
before update on public.admin_shell_commands
for each row execute function public.admin_shell_touch_updated_at();

create or replace function public.admin_shell_set_actor_member()
returns trigger
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
begin
  if new.actor_member_id is null then
    new.actor_member_id := public.current_actor_member_id();
  end if;
  return new;
end;
$$;

drop trigger if exists trg_admin_shell_sessions_set_actor_member on public.admin_shell_sessions;
create trigger trg_admin_shell_sessions_set_actor_member
before insert on public.admin_shell_sessions
for each row execute function public.admin_shell_set_actor_member();

alter table public.admin_shell_sessions enable row level security;
alter table public.admin_shell_commands enable row level security;
alter table public.admin_shell_output enable row level security;

grant select, insert, update, delete on public.admin_shell_sessions to authenticated;
grant select, insert, update, delete on public.admin_shell_commands to authenticated;
grant select, insert on public.admin_shell_output to authenticated;
grant usage, select on sequence public.admin_shell_output_id_seq to authenticated;

drop policy if exists "Internal admins manage own shell sessions" on public.admin_shell_sessions;
create policy "Internal admins manage own shell sessions"
on public.admin_shell_sessions
for all
to authenticated
using (
  public.is_internal_admin()
  and created_by_auth_id = auth.uid()
)
with check (
  public.is_internal_admin()
  and created_by_auth_id = auth.uid()
);

drop policy if exists "Internal admins manage own shell commands" on public.admin_shell_commands;
create policy "Internal admins manage own shell commands"
on public.admin_shell_commands
for all
to authenticated
using (
  public.is_internal_admin()
  and created_by_auth_id = auth.uid()
  and exists (
    select 1
    from public.admin_shell_sessions s
    where s.id = admin_shell_commands.session_id
      and s.created_by_auth_id = auth.uid()
  )
)
with check (
  public.is_internal_admin()
  and created_by_auth_id = auth.uid()
  and exists (
    select 1
    from public.admin_shell_sessions s
    where s.id = admin_shell_commands.session_id
      and s.created_by_auth_id = auth.uid()
  )
);

drop policy if exists "Internal admins read own shell output" on public.admin_shell_output;
create policy "Internal admins read own shell output"
on public.admin_shell_output
for select
to authenticated
using (
  public.is_internal_admin()
  and exists (
    select 1
    from public.admin_shell_sessions s
    where s.id = admin_shell_output.session_id
      and s.created_by_auth_id = auth.uid()
  )
);

drop policy if exists "Internal admins insert own shell output" on public.admin_shell_output;
create policy "Internal admins insert own shell output"
on public.admin_shell_output
for insert
to authenticated
with check (
  public.is_internal_admin()
  and created_by_auth_id = auth.uid()
  and exists (
    select 1
    from public.admin_shell_sessions s
    where s.id = admin_shell_output.session_id
      and s.created_by_auth_id = auth.uid()
  )
);
